name = "cdn-manager-worker777"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./public"

[vars]
GITHUB_USER = "juniorvilhalva11-lab"
GITHUB_REPO = "testedosguripae"
GITHUB_BRANCH = "main"

[[d1_databases]]
binding = "DB"
database_name = "cdn_manager_db"
database_id = "9c763f1e-6f93-40c7-ab6b-d3224e4e9ea3"
preview_database_id = "DB"
